/*
 * @author VRUSHABH
 */
package typesconstructor;

public class ExampleClass2 {

    private int number;
    private String name;
    private float var;

    /*
           In this class we have two constructors, one with no parameters is the default constructor.
           and the other one is paramaterized constructor which takes two parameters.
           explaination below.
     */
    public ExampleClass2() {
        /*
            This constructor is called default constructor because it initializes the values of instance variales
        to their default values. u can also remember a default constructor as a constructor that initializes the values of the 
        instance variables to their default values. The one in the pervious class is does the same thing, but it was not written by 
        the programmer, auto generated by compiler but they r the same thing.
         */
    }

    public ExampleClass2(String name, int number) {
        /*
            This Constructor is called paramaterized constructor as it takes parameters when called 
            and then intializes the instances variables to the parameters passed thats the reason when we 
            create an object of this class and pass in the parameters/arguments we initialize the instance variables.
             by doing the following things. but if suppose there were some variables whose values were not passed
              they get initialized to their default values, like here is the "var " variable. but this still called a paramaterized 
              constructor. so to remember : if any constructor takes any no. of  parameters when called it is a 
              "paramaterized constructor"
         */

        this.name = name;
        this.number = number;
    }

    //method to print instance variable values.
    public void printVals() {
        System.out.println("name: " + this.name + " number: " + this.number + " var: " + var);
    }
}
